language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.3

env:
  matrix:
    - ES_COMPOSER_NODEV=no
    - ES_COMPOSER_NODEV=yes

install:
  - /bin/bash ansible/provision.sh

before_script:
  - mkdir -p build/logs

script:
  - phpunit -c test/

after_script:
  - cat /var/log/elasticsearch/*.log
  - cat /var/log/nginx/*.log
  - cat build/logs/phpunit-tap.log
  - php vendor/bin/coveralls -v
